version: '2'

volumes:
  peer1.org1.log-network:

networks:
  byfn:

services:

  peer2.org1.log-network:
    container_name: peer1.org1.log-network
    extends:
      file:  base3/docker-compose-base.yaml
      service: peer2.org1.log-network
    networks:
      - byfn

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
      - byfn
