version: '2'

volumes:
  orderer.log-network:
  peer0.org1.log-network:
  peer1.org1.log-network:
  peer2.org1.log-network:

networks:
  byfn:

services:

  orderer.log-network:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.log-network
    container_name: orderer.log-network
    networks:
      - byfn

  peer0.org1.log-network:
    container_name: peer0.org1.log-network
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.log-network
    networks:
      - byfn

  peer1.org1.log-network:
    container_name: peer1.org1.log-network
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.log-network
    networks:
      - byfn

  peer2.org1.log-network:
    container_name: peer2.org1.log-network
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.org1.log-network
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.log-network:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.log-network/users/Admin@org1.log-network/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.log-network
      - peer0.org1.log-network
      - peer1.org1.log-network
      - peer2.org1.log-network
    networks:
      - byfn
