# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.log-network-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/5ccdeb0717ff5bc77741c396361999e9a336310168ffeeb32007cb05984b07b1_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.log-network/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn