version: '2'

volumes:
  peer1.org1.log-network:

networks:
  byfn:

services:

  #zookeeper1:
  #  container_name: zookeeper1
  #  image: hyperledger/fabric-zookeeper
  #  environment:
  #       - ZOO_MY_ID=2
  #       - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
  #  ports:
  #       - 2181
  #       - 2888
  #       - 3888
  #  networks:
  #       - byfn

  #kafka1:
  #      image: hyperledger/fabric-kafka
  #      container_name: kafka1
  #      environment:
  #          - KAFKA_LOG_RETENTION_MS=-1
  #          - KAFKA_MESSAGE_MAX_BYTES=103809024
  #          - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
  #          - KAFKA_BROKER_ID=1
  #          - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #          - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
  #          - KAFKA_DEFAULT_REPLICATION_FACTOR=3
  #          - KAFKA_MIN_INSYNC_REPLICAS=2
  #          - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
  #      ports:
  #          - 9092
  #      depends_on:
  #          - zookeeper0
  #          - zookeeper1
  #          - zookeeper2
  #      links:
  #          - zookeeper0:zookeeper0
  #          - zookeeper1:zookeeper1
  #          - zookeeper2:zookeeper2
  #      networks:
  #          - byfn

  peer1.org1.log-network:
    container_name: peer1.org1.log-network
    extends:
      file:  base2/docker-compose-base.yaml
      service: peer1.org1.log-network
    networks:
      - byfn

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 6984:5984
    networks:
      - byfn
